name: Build and Deploy the SPFx WebPart with Microsoft 365 CLI

on: [push]

env:
  SolutionFolder: ./solution
  SolutionPackagePath: solution/sharepoint/solution/solution.sppkg

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    
    - name: Run npm ci
      run: npm ci
      working-directory: ${{ env.SolutionFolder }}
    
    - name: Run npm i -g gulp
      run: npm i -g gulp
      working-directory: ${{ env.SolutionFolder }}
    
    - name: Bundle and package
      run: |
        gulp bundle --ship
        gulp package-solution --ship
      working-directory: ${{ env.SolutionFolder }}

    - name: CLI for Microsoft 365 login
      uses: pnp/action-cli-login@v2.0.0
      with:
        ADMIN_USERNAME:  'sharepoint@fhchumcommerce.onmicrosoft.com'
        ADMIN_PASSWORD:  'humc@110924'
